# Generated by scripts/module-generate. Do not edit.

from core_kernel import backend_module_contribution as core_kernel_contribution
from module_runtime import backend_module_contribution as module_runtime_contribution
from runtime_fixture import backend_module_contribution as runtime_fixture_contribution

GENERATED_BACKEND_MODULE_CATALOG = (
    core_kernel_contribution,  # core-kernel
    module_runtime_contribution,  # module-runtime
    runtime_fixture_contribution,  # runtime-fixture
)

GENERATED_BACKEND_MODULE_IDS = tuple(
    contribution["manifest"]["id"]
    for contribution in GENERATED_BACKEND_MODULE_CATALOG
)
